# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: 28.0.4

services:
  mongo.catalog:
    image: mongo
    container_name: mongo-catalog
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  play.catalog.mq:
    image: rabbitmq:management
    container_name: CatalogQueue
    ports:
      - 5672:5672
      - 15672:15672
    hostname: catalog-queue
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  mongodbdata:
  rabbitmqdata: